// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/check-availability.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/booking.ts
var BOOKING_BASE_URL = "https://frame2.hotelpms.io/BookingFrameClient/hotel/4999DCF40A49BFB3D5A6C22E1174000D/e2d8af9e-82cf-4b24-ba19-fc7b08142f0e/book/rooms";
function buildBookingUrl(checkin, checkout, adults, children = 0, babies = 0) {
  const params = new URLSearchParams();
  params.set("currency", "ARS");
  params.set("language", "es-ES");
  params.set("from", checkin);
  params.set("to", checkout);
  params.set("nAdults", String(adults));
  if (children > 0) params.set("nChilds", String(children));
  if (babies > 0) params.set("nBabies", String(babies));
  params.set("rp", "");
  return `${BOOKING_BASE_URL}?${params.toString()}`;
}
var isoDate = /^\d{4}-\d{2}-\d{2}$/;

// src/lib/mcp/tools/check-availability.ts
var toSuggestion = (s) => ({ checkin: s.checkin, checkout: s.checkout, nights: s.nights });
var check_availability_default = defineTool({
  name: "check_availability",
  title: "Consultar disponibilidad",
  description: "Check Esmeralda Apart availability for a date range and get a direct booking link plus alternative dates.",
  inputSchema: {
    checkin: z.string().regex(isoDate).describe("Check-in date, YYYY-MM-DD."),
    checkout: z.string().regex(isoDate).describe("Check-out date, YYYY-MM-DD."),
    adults: z.number().int().min(1).max(4).default(2).describe("Adults (+4 years)."),
    children: z.number().int().min(0).max(3).default(0).describe("Children occupying a bed."),
    babies: z.number().int().min(0).max(2).default(0).describe("Babies under 1 year (no bed).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ checkin, checkout, adults, children, babies }) => {
    if (checkout <= checkin) throw new ToolError("checkout must be after checkin");
    if (adults + children > 4) throw new ToolError("Maximum capacity is 4 guests (adults + children).");
    const { data, error } = await supabaseAnon().functions.invoke("check-availability", {
      body: { checkin, checkout }
    });
    if (error || !data) throw new ToolError("Could not check availability right now. Try again later.");
    const result = {
      available: data.available,
      checkin: data.checkin,
      checkout: data.checkout,
      nights: data.nights,
      bookingUrl: data.available ? buildBookingUrl(checkin, checkout, adults, children, babies) : null,
      extensions: (data.extensions ?? []).map(toSuggestion),
      alternativesBefore: (data.before ?? []).map(toSuggestion),
      alternativesAfter: (data.after ?? []).map(toSuggestion)
    };
    const text = data.available ? `Available ${checkin} \u2192 ${checkout} (${data.nights} nights). Book: ${result.bookingUrl}` : `Not available ${checkin} \u2192 ${checkout}. See alternative dates.`;
    return { content: [{ type: "text", text }], structuredContent: result };
  }
});

// src/lib/mcp/tools/get-property-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
var info = {
  name: "Esmeralda Apart",
  city: "Marcos Ju\xE1rez, C\xF3rdoba, Argentina",
  website: "https://esmeraldaapart.com.ar",
  whatsapp: "https://wa.me/5493472433334",
  maxGuests: 4,
  guestRules: "Up to 4 guests occupying a bed (adults + children). Babies under 1 year do not count.",
  checkIn: "Automatic 24h self check-in; usual entry from 14:00. Access instructions sent via WhatsApp.",
  amenities: ["Private bathroom", "Hot/cold air conditioning", "Wi-Fi", "Smart TV", "Equipped kitchen (fridge, stove, microwave, tableware)"],
  motorcycleParking: "Parking space for motorcycles, to be coordinated in advance and subject to availability.",
  bookingPolicy: "Same-day bookings are not accepted after 22:00 (Argentina time)."
};
var get_property_info_default = defineTool2({
  name: "get_property_info",
  title: "Informaci\xF3n del alojamiento",
  description: "Get verified information about Esmeralda Apart: location, amenities, capacity, check-in and contact.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
    structuredContent: { ...info, amenities: [...info.amenities] }
  })
});

// src/lib/mcp/tools/get-booking-link.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^4.6.5";
var get_booking_link_default = defineTool3({
  name: "get_booking_link",
  title: "Enlace de reserva",
  description: "Build the direct booking-engine link for given dates and guests (does not check availability).",
  inputSchema: {
    checkin: z2.string().regex(isoDate).describe("Check-in date, YYYY-MM-DD."),
    checkout: z2.string().regex(isoDate).describe("Check-out date, YYYY-MM-DD."),
    adults: z2.number().int().min(1).max(4).default(2),
    children: z2.number().int().min(0).max(3).default(0),
    babies: z2.number().int().min(0).max(2).default(0)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ checkin, checkout, adults, children, babies }) => {
    if (checkout <= checkin) throw new ToolError2("checkout must be after checkin");
    if (adults + children > 4) throw new ToolError2("Maximum capacity is 4 guests (adults + children).");
    const url = buildBookingUrl(checkin, checkout, adults, children, babies);
    return { content: [{ type: "text", text: url }], structuredContent: { url } };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "esmeralda-apart",
  title: "Esmeralda Apart",
  version: "0.1.0",
  instructions: "Tools for Esmeralda Apart, apartments in Marcos Ju\xE1rez (C\xF3rdoba, Argentina). Use `get_property_info` for verified details, `check_availability` to check dates and get a booking link, and `get_booking_link` to build a booking URL. Never invent facts about the property.",
  tools: [check_availability_default, get_property_info_default, get_booking_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
