import type { HubEntry } from "./types";

// Editorial rule: no invented business names, phone numbers, prices or opening
// hours. Everything here describes categories and verifiable city-level facts.

export const gastronomia: HubEntry[] = [
  {
    cluster: "gastronomia",
    slug: "donde-comer-en-marcos-juarez",
    title: "Dónde comer en Marcos Juárez: guía gastronómica",
    h1: "Dónde comer en Marcos Juárez",
    description:
      "Guía para comer en Marcos Juárez: parrillas, pizzerías, restaurantes de cocina casera, cafeterías y bares, con horarios típicos y qué esperar en cada franja.",
    keywords: "donde comer en Marcos Juárez, restaurantes Marcos Juárez, gastronomía Marcos Juárez",
    image: "/images/experience.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "En Marcos Juárez se come sobre todo en el centro: parrillas de carne a la parrilla y achuras, pizzerías al molde y a la piedra, restaurantes de cocina casera con pastas, cafeterías para desayuno y merienda, y bares que abren de noche.",
    body: [
      { type: "p", text: "La oferta gastronómica de Marcos Juárez se concentra en pocas cuadras alrededor de la plaza principal y las avenidas de acceso al centro. Eso simplifica todo: si te alojás en el centro, casi cualquier opción queda a distancia caminable." },
      { type: "h2", text: "Cómo funcionan los horarios en la ciudad" },
      { type: "p", text: "Marcos Juárez sigue el ritmo de las ciudades del interior de Córdoba: mediodía fuerte, siesta comercial y noche que arranca tarde. Como referencia general —siempre conviene confirmar con cada local— el almuerzo se sirve alrededor del mediodía y la cena rara vez empieza antes de las 21." },
      {
        type: "table",
        caption: "Franjas horarias típicas de la ciudad (referencia general, no horarios de un local concreto)",
        headers: ["Momento", "Qué encontrás", "Franja habitual"],
        rows: [
          ["Desayuno", "Cafeterías y panaderías", "Mañana temprano"],
          ["Almuerzo", "Parrillas, cocina casera, menú del día", "Mediodía"],
          ["Merienda", "Cafeterías, confiterías, heladerías", "Media tarde"],
          ["Cena", "Parrillas, pizzerías, restaurantes", "A partir de las 21"],
          ["Después de cenar", "Bares y cervecerías", "Noche, fines de semana"],
        ],
      },
      { type: "h2", text: "Qué tipo de comida vas a encontrar" },
      { type: "ul", items: [
        "Parrilla: asado, tira, vacío, achuras y provoleta, la categoría más representativa del sudeste cordobés.",
        "Pastas caseras: sorrentinos, ravioles y ñoquis, muy presentes en los menús de mediodía.",
        "Pizza: al molde y a la piedra, en general con servicio de delivery.",
        "Cocina rápida: milanesas, hamburguesas y lomitos, la opción más común para cenar tarde.",
        "Café de especialidad y panadería, en crecimiento en el casco céntrico.",
      ]},
      { type: "h2", text: "Comer con cocina propia" },
      { type: "p", text: "Si viajás varios días por trabajo o en familia, alternar salidas con comidas en el departamento baja mucho el gasto. Los departamentos de Esmeralda Apart tienen cocina equipada con heladera, anafe, microondas y vajilla, y hay supermercados a pocas cuadras." },
      { type: "h2", text: "Recomendación práctica" },
      { type: "p", text: "En días de expo, feria o torneo la ciudad se llena y los locales del centro trabajan al límite: conviene cenar temprano o reservar mesa. Fuera de esas fechas, un miércoles a la noche la oferta abierta es más acotada que un fin de semana." },
      { type: "quote", text: "Consultá disponibilidad en la barra inferior: alojarte en el centro te deja la zona gastronómica a pocas cuadras." },
    ],
    faqs: [
      { q: "¿A qué hora se cena en Marcos Juárez?", a: "Como en la mayoría de las ciudades del interior de Córdoba, la cena arranca tarde: la franja habitual empieza alrededor de las 21. Conviene confirmar el horario del local antes de salir." },
      { q: "¿Hay delivery en Marcos Juárez?", a: "Sí. Pizzerías, rotiserías y locales de comida rápida trabajan con envío a domicilio dentro del casco céntrico, en general por WhatsApp o por aplicaciones de mensajería." },
      { q: "¿Se puede comer bien caminando desde el centro?", a: "Sí. La oferta gastronómica está concentrada alrededor de la plaza principal y las calles comerciales, así que alojándote en el centro no necesitás el auto para salir a comer." },
      { q: "¿Conviene tener cocina en el alojamiento?", a: "Si te quedás más de dos noches, sí: permite resolver desayunos y alguna cena sin salir y reduce el gasto diario. Todos los departamentos de Esmeralda Apart tienen cocina equipada." },
    ],
    related: ["gastronomia/parrillas", "gastronomia/cafeterias-de-especialidad", "turismo/que-hacer-en-marcos-juarez"],
    relatedPosts: ["que-hacer-en-marcos-juarez"],
  },
  {
    cluster: "gastronomia",
    slug: "parrillas",
    title: "Parrillas en Marcos Juárez: dónde comer asado",
    h1: "Parrillas en Marcos Juárez",
    description:
      "Cómo es la propuesta de parrillas en Marcos Juárez: cortes típicos, formatos de servicio, horarios habituales y qué tener en cuenta si venís en grupo.",
    keywords: "parrillas Marcos Juárez, asado Marcos Juárez, donde comer carne Marcos Juárez",
    image: "/images/spaces.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "Las parrillas son la categoría gastronómica más fuerte de Marcos Juárez: asado, tira de asado, vacío, matambre, achuras y provoleta, servidos al plato o por porción, con la cena arrancando alrededor de las 21.",
    body: [
      { type: "p", text: "Estamos en el corazón agrícola-ganadero del sudeste de Córdoba, y eso se nota en la mesa. La parrilla es el formato por defecto cuando alguien invita a cenar afuera en Marcos Juárez, tanto para una comida de trabajo como para una salida familiar." },
      { type: "h2", text: "Qué pedir" },
      { type: "ul", items: [
        "Asado de tira y vacío: los cortes más pedidos.",
        "Bife de chorizo y entraña, habituales en cartas más completas.",
        "Achuras: chinchulines, mollejas y morcilla, normalmente como entrada.",
        "Provoleta y empanadas para abrir la mesa.",
        "Guarniciones simples: papas fritas, ensalada mixta, puré.",
      ]},
      { type: "h2", text: "Formatos de servicio" },
      { type: "p", text: "Vas a encontrar tres modalidades: parrilla de mesa con carta, parrilla libre en algunas noches puntuales, y parrilla al paso o take away para llevar. Para grupos grandes —delegaciones deportivas o comitivas de trabajo— siempre conviene avisar con anticipación." },
      { type: "h2", text: "Si venís en delegación" },
      { type: "p", text: "Los fines de semana con torneo la demanda se dispara. Si viajás con un plantel o un grupo de más de ocho personas, coordinar la mesa con un día de anticipación evita esperas largas. Desde Esmeralda Apart te podemos orientar por WhatsApp sobre qué está abierto según el día." },
      { type: "quote", text: "Departamentos en el centro, a pocas cuadras de la zona de parrillas. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Cuánto sale comer en una parrilla en Marcos Juárez?", a: "Los precios varían según el local y la temporada, así que conviene consultarlos directamente. Como referencia, están en línea con los de otras ciudades medianas del interior de Córdoba." },
      { q: "¿Las parrillas abren al mediodía?", a: "Varias trabajan al mediodía con menú del día además del servicio de noche, pero no todas. Es la información que más cambia, así que verificalo con el local el mismo día." },
      { q: "¿Se puede pedir asado para llevar?", a: "Sí, es habitual el formato take away, muy práctico si te alojás en un departamento con cocina y mesa propia." },
    ],
    related: ["gastronomia/donde-comer-en-marcos-juarez", "gastronomia/pizzerias", "alojamiento/hospedaje-para-deportistas"],
  },
  {
    cluster: "gastronomia",
    slug: "pizzerias",
    title: "Pizzerías en Marcos Juárez: pizza, delivery y noche",
    h1: "Pizzerías en Marcos Juárez",
    description:
      "Pizzerías en Marcos Juárez: estilos de pizza, servicio en salón, take away y delivery al centro, y por qué es la opción más práctica para cenar tarde.",
    keywords: "pizzerias Marcos Juárez, pizza Marcos Juárez, delivery pizza Marcos Juárez",
    image: "/images/amenities.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "Las pizzerías de Marcos Juárez trabajan pizza al molde y a la piedra, con servicio en salón, take away y delivery al casco céntrico. Es la opción más disponible para cenar tarde, sobre todo entre semana.",
    body: [
      { type: "p", text: "Si llegás de noche a la ciudad después de manejar por la Au Ruta 9, la pizzería suele ser la salida más segura: es la categoría con horarios más extendidos y con delivery activo casi todos los días." },
      { type: "h2", text: "Estilos que vas a encontrar" },
      { type: "ul", items: [
        "Pizza al molde, de masa alta y abundante muzzarella, el estilo dominante.",
        "Pizza a la piedra, de masa fina, más habitual en locales con horno de barro o eléctrico.",
        "Fugazzeta, napolitana y calabresa entre las variedades clásicas.",
        "Empanadas, casi siempre en la misma carta.",
      ]},
      { type: "h2", text: "Delivery al centro" },
      { type: "p", text: "El reparto a domicilio dentro del casco céntrico funciona bien y en general se coordina por WhatsApp. Si te alojás en Esmeralda Apart, el pedido llega directo a la puerta del edificio: es la alternativa más cómoda cuando llegás tarde y no querés volver a salir." },
      { type: "h2", text: "Cenar tarde llegando por la Ruta 9" },
      { type: "p", text: "El check-in digital 24 horas del apart resuelve la llegada a cualquier hora, y la pizza a domicilio resuelve la cena. Es la combinación más usada por quienes cortan el viaje entre Rosario y Córdoba." },
      { type: "quote", text: "Llegás tarde, entrás con tu código y cenás sin volver a salir. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Hay delivery de pizza en Marcos Juárez?", a: "Sí. Varias pizzerías reparten dentro del casco céntrico, habitualmente coordinando el pedido por WhatsApp o por aplicaciones de mensajería." },
      { q: "¿Hasta qué hora se puede pedir?", a: "Depende de cada local y del día de la semana; los fines de semana el servicio se extiende más. Conviene consultar el horario del local antes de pedir." },
      { q: "¿Puedo recibir el pedido en el departamento?", a: "Sí. El delivery llega a la puerta del edificio y podés recibirlo sin inconvenientes a cualquier hora en la que el local esté operando." },
    ],
    related: ["gastronomia/donde-comer-en-marcos-juarez", "rutas/donde-descansar-viajando-por-ruta-9", "servicios/check-in-digital"],
  },
  {
    cluster: "gastronomia",
    slug: "cafeterias-de-especialidad",
    title: "Cafeterías en Marcos Juárez: café, desayuno y merienda",
    h1: "Cafeterías en Marcos Juárez",
    description:
      "Cafeterías en Marcos Juárez: dónde desayunar y merendar en el centro, qué esperar del café de especialidad y opciones para trabajar con notebook.",
    keywords: "cafeterias Marcos Juárez, cafe de especialidad Marcos Juárez, donde desayunar Marcos Juárez",
    image: "/images/design.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "Las cafeterías de Marcos Juárez se concentran en el centro y alrededor de la plaza principal. Ofrecen desayunos, meriendas, café de especialidad en los locales más nuevos y, en varios casos, WiFi para trabajar un rato.",
    body: [
      { type: "p", text: "En los últimos años el café de especialidad llegó también a las ciudades medianas del interior, y Marcos Juárez no fue la excepción. Conviven las confiterías tradicionales, de café clásico con medialunas, con propuestas más nuevas de grano tostado y métodos alternativos." },
      { type: "h2", text: "Desayuno" },
      { type: "p", text: "El desayuno típico es café con leche y medialunas o tostados. Las panaderías del centro abren temprano y son la opción más económica si preferís desayunar en el departamento." },
      { type: "h2", text: "Trabajar desde una cafetería" },
      { type: "p", text: "Si viajás por trabajo y necesitás una reunión corta fuera del alojamiento, varias cafeterías del centro funcionan bien para eso en horario de mañana. Para videollamadas o trabajo concentrado, el departamento con WiFi de fibra y escritorio es más confiable." },
      { type: "h2", text: "Merienda" },
      { type: "p", text: "La franja de la tarde es fuerte en la ciudad: después de la siesta, las confiterías y heladerías del centro se llenan. Es un buen momento para caminar la plaza y la zona comercial." },
      { type: "quote", text: "Departamentos con cafetera y WiFi de fibra, a pocas cuadras de la plaza. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Hay café de especialidad en Marcos Juárez?", a: "Sí, hay propuestas de café de especialidad en el centro, además de las confiterías tradicionales de café clásico con medialunas." },
      { q: "¿Puedo trabajar con la notebook en una cafetería?", a: "Varias cafeterías del centro tienen WiFi y funcionan bien para trabajo liviano por la mañana. Para videollamadas conviene el departamento, que tiene fibra óptica y escritorio." },
      { q: "¿El alojamiento incluye desayuno?", a: "Esmeralda Apart no sirve desayuno, pero cada departamento tiene cocina equipada y hay panaderías y cafeterías a pocas cuadras." },
    ],
    related: ["gastronomia/donde-comer-en-marcos-juarez", "servicios/wifi", "alojamiento/mejor-alojamiento-para-empresas"],
  },
  {
    cluster: "gastronomia",
    slug: "bares-y-cervecerias",
    title: "Bares y cervecerías en Marcos Juárez",
    h1: "Bares y cervecerías en Marcos Juárez",
    description:
      "Bares y cervecerías en Marcos Juárez: qué esperar de la noche, en qué días hay más movimiento y cómo volver caminando al alojamiento en el centro.",
    keywords: "bares Marcos Juárez, cervecerias Marcos Juárez, salir de noche Marcos Juárez",
    image: "/images/gallery3.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "La noche de Marcos Juárez se concentra en bares y cervecerías del centro, con más movimiento los viernes y sábados. La cerveza artesanal y las picadas son la propuesta más común, en horarios que arrancan después de cenar.",
    body: [
      { type: "p", text: "La salida nocturna en Marcos Juárez es tranquila y de escala barrial: bares con mesas afuera cuando el clima acompaña, cervecerías con tap de artesanal y picadas para compartir. El movimiento fuerte es de jueves a sábado." },
      { type: "h2", text: "Qué esperar" },
      { type: "ul", items: [
        "Cerveza artesanal de producción regional en cervecerías del centro.",
        "Picadas, papas y hamburguesas como comida acompañante.",
        "Música en vivo ocasional los fines de semana.",
        "Horarios que arrancan tarde, después de la franja de cena.",
      ]},
      { type: "h2", text: "Volver caminando" },
      { type: "p", text: "Una de las ventajas de alojarse en el centro es no depender del auto para salir de noche. Desde Esmeralda Apart, los bares de la zona céntrica quedan a pocas cuadras y el regreso es caminando." },
      { type: "h2", text: "Si venís en grupo" },
      { type: "p", text: "Para grupos de trabajo o delegaciones, la cervecería suele ser el plan más práctico después de la cena. Recordá que el departamento tiene acceso electrónico personalizado y no hay horario de recepción: podés volver a la hora que quieras." },
      { type: "quote", text: "Sin horario de recepción y a pocas cuadras del centro. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Hay vida nocturna en Marcos Juárez?", a: "Sí, aunque es tranquila: bares y cervecerías del centro con más movimiento de jueves a sábado, y algunos boliches que funcionan los fines de semana." },
      { q: "¿Puedo volver tarde al alojamiento?", a: "Sí. Esmeralda Apart funciona con acceso electrónico personalizado las 24 horas, sin recepción ni horario límite de entrada." },
      { q: "¿Los bares están cerca del centro?", a: "La mayoría de la propuesta nocturna está en el casco céntrico, a distancia caminable desde el apart." },
    ],
    related: ["turismo/vida-nocturna", "gastronomia/donde-comer-en-marcos-juarez", "servicios/seguridad"],
  },
  {
    cluster: "gastronomia",
    slug: "panaderias-y-heladerias",
    title: "Panaderías y heladerías en Marcos Juárez",
    h1: "Panaderías y heladerías en Marcos Juárez",
    description:
      "Panaderías y heladerías en Marcos Juárez: qué comprar para el desayuno o la merienda, cómo se organizan los horarios y opciones cerca del centro.",
    keywords: "panaderias Marcos Juárez, heladerias Marcos Juárez, facturas Marcos Juárez",
    image: "/images/gallery5.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "Las panaderías de Marcos Juárez abren temprano y venden facturas, pan casero y sándwiches; las heladerías concentran su movimiento en la tarde y la noche, sobre todo en verano y los fines de semana.",
    body: [
      { type: "p", text: "Si te alojás en un departamento con cocina, la panadería del barrio se vuelve parte de la rutina: facturas y pan a la mañana, algo dulce para la merienda. Es la forma más económica de resolver desayunos en un viaje de varios días." },
      { type: "h2", text: "Panaderías" },
      { type: "ul", items: [
        "Facturas y medialunas, la compra clásica de la mañana.",
        "Pan francés, casero y de campo.",
        "Sándwiches de miga y pizzetas, habituales al mediodía.",
        "Tortas y postres por encargo para cumpleaños o eventos.",
      ]},
      { type: "h2", text: "Heladerías" },
      { type: "p", text: "En verano, la heladería es la salida familiar por excelencia después de la cena. La mayoría trabaja con envase para llevar y varias ofrecen envío a domicilio dentro del centro." },
      { type: "h2", text: "Con niños" },
      { type: "p", text: "Plaza, heladería y vuelta caminando es el plan más simple y efectivo para una tarde en familia en Marcos Juárez, y no requiere planificar nada." },
      { type: "quote", text: "Departamentos con cocina equipada y heladera con freezer, en pleno centro. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Las panaderías abren los domingos?", a: "Muchas abren al menos en horario de mañana, pero varía según el local. Conviene confirmarlo el mismo día." },
      { q: "¿Hay heladerías con delivery?", a: "Sí, varias heladerías reparten dentro del casco céntrico durante la temporada de calor." },
      { q: "¿Puedo guardar helado en el departamento?", a: "Sí. Todos los departamentos cuentan con heladera con freezer y cocina equipada." },
    ],
    related: ["gastronomia/donde-comer-en-marcos-juarez", "servicios/cocina-equipada", "alojamiento/hospedaje-para-familias"],
  },
  {
    cluster: "gastronomia",
    slug: "comer-cerca-de-esmeralda-apart",
    title: "Dónde comer cerca de Esmeralda Apart",
    h1: "Dónde comer cerca de Esmeralda Apart",
    description:
      "Opciones para comer a pocas cuadras de Esmeralda Apart, en 9 de Julio 262, Marcos Juárez: gastronomía céntrica caminable, delivery y supermercados.",
    keywords: "donde comer cerca de Esmeralda Apart, restaurantes cerca del centro Marcos Juárez, comer cerca de mí Marcos Juárez",
    image: "/images/apartment.jpg",
    updatedAt: "2026-07-25",
    snippet:
      "Esmeralda Apart está en 9 de Julio 262, en pleno centro de Marcos Juárez: la zona gastronómica, la plaza principal, panaderías y supermercados quedan a pocas cuadras, todo caminable y con delivery disponible a la puerta.",
    body: [
      { type: "p", text: "La ubicación céntrica es lo que hace que no necesites el auto para comer. Desde la puerta del apart, la plaza principal y las calles comerciales quedan a pocos minutos a pie, y ahí está concentrada casi toda la oferta gastronómica de la ciudad." },
      { type: "h2", text: "A pocas cuadras" },
      { type: "ul", items: [
        "Parrillas y restaurantes de cocina casera en la zona céntrica.",
        "Pizzerías con salón y delivery.",
        "Cafeterías y panaderías para desayuno y merienda.",
        "Supermercados para abastecer la cocina del departamento.",
        "Bares y cervecerías para después de la cena.",
      ]},
      { type: "h2", text: "Si llegás tarde" },
      { type: "p", text: "El check-in digital funciona las 24 horas y el delivery llega a la puerta del edificio, así que una llegada de madrugada por la Au Ruta 9 se resuelve sin depender de horarios de recepción." },
      { type: "h2", text: "Si te quedás varios días" },
      { type: "p", text: "Con cocina equipada podés alternar: comprar en el supermercado para desayunos y alguna cena, y salir a comer el resto. Es la fórmula que mejor funciona en estadías de trabajo largas." },
      { type: "quote", text: "9 de Julio 262, Marcos Juárez. Todo el centro a pocas cuadras. Consultá disponibilidad en la barra inferior." },
    ],
    faqs: [
      { q: "¿Dónde está ubicado Esmeralda Apart?", a: "En 9 de Julio 262, Marcos Juárez, Córdoba, en pleno centro y a pocas cuadras de la plaza principal y de la zona gastronómica y comercial." },
      { q: "¿Hay supermercados cerca?", a: "Sí, hay supermercados dentro del casco céntrico, a distancia caminable desde el apart." },
      { q: "¿Puedo pedir delivery al departamento?", a: "Sí. Los repartos llegan a la puerta del edificio y podés recibirlos sin restricciones de horario del alojamiento." },
      { q: "¿Necesito auto para moverme?", a: "No para el centro: todo lo esencial está a pocas cuadras. Si venís en auto, coordinamos cochera." },
    ],
    place: {
      address: "9 de Julio 262, Marcos Juárez, Córdoba",
      mapQuery: "9 de Julio 262, Marcos Juárez, Córdoba",
      distanceKm: "0 km",
      driveMinutes: "—",
      walkMinutes: "Punto de partida",
      placeType: "LocalBusiness",
    },
    related: ["gastronomia/donde-comer-en-marcos-juarez", "servicios-en-marcos-juarez/supermercados", "servicios/cochera"],
  },
];
